export const images = {
  joker: require('./joker.png'),
  timer: require('./timer.png'),
  search: require('./search.png'),
  mark: require('./mark.png'),
  redShirt: require('./redShirt.png'),
  shield: require('./shield.png'),
  ligth: require('./ligth.png'),
  card: require('./card.png'),
  card2: require('./card2.png'),
  star: require('./star.png'),
  pack: require('./pack.png'),
  crown: require('./crown.png'),
  league: require('./league.png'),
  gem: require('./gem.png'),
  cards: require('./cards.png'),
  arrowRigth: require('./arrowRigth.png'),
  leftFlag: require('./leftFlag.png'),
  rigthFlag: require('./rigthFlag.png'),
};
